---
- name: Configure /etc/locale.gen
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^#?{{ item }}$"
    line: "{{ item }}"
    state: present
  loop: "{{ locale_additional }}"

- name: Generate selected locales
  ansible.builtin.command: locale-gen
  changed_when: false

- name: Configure /etc/default/locale
  ansible.builtin.copy:
    dest: /etc/default/locale
    content: |
      LANG={{ locale_default }}
      LC_ALL={{ locale_default }}
    mode: '0644'

- name: Reconfigure locales
  ansible.builtin.command: dpkg-reconfigure -f noninteractive locales
  changed_when: false
